<h2>Tensorflow Simple Functions</h2>

In [15]:
import tensorflow as tf

In [16]:
x = tf.constant(4,shape=(1,1),dtype=tf.float64)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float64)


In [17]:
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [18]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [19]:
x = tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [20]:
x = tf.eye(3)
print(x)
x = tf.eye(2)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)


In [21]:
x = tf.random.normal((3,3),mean=0,stddev=1)
print(x)

tf.Tensor(
[[ 2.3303792   1.6047904   0.8068755 ]
 [ 0.7821822  -0.43178803 -1.0748575 ]
 [ 0.28839055 -0.6056937   0.67822623]], shape=(3, 3), dtype=float32)


In [22]:
x = tf.random.uniform((1,3),minval=0,maxval=1)
print(x)

tf.Tensor([[0.46780515 0.8787869  0.15474713]], shape=(1, 3), dtype=float32)


In [23]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [24]:
x = tf.range(start=1,limit=10,delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [25]:
x = tf.cast(x,dtype=tf.float64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


<h2>Mathematical Operations</h2>

In [28]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])
sum = tf.add(x,y)
print(x,"\n",y,"\n",sum)

tf.Tensor([1 2 3], shape=(3,), dtype=int32) 
 tf.Tensor([4 5 6], shape=(3,), dtype=int32) 
 tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [29]:
difference = tf.subtract(y,x)
print(difference)

tf.Tensor([3 3 3], shape=(3,), dtype=int32)


In [30]:
difference = y-x
print(difference)

tf.Tensor([3 3 3], shape=(3,), dtype=int32)


In [31]:
x = tf.constant([3,8,10])
y = tf.constant([6,16,20])

In [32]:
division = y / x
print(division)
division = tf.divide(y,x)
print(division)

tf.Tensor([2. 2. 2.], shape=(3,), dtype=float64)
tf.Tensor([2. 2. 2.], shape=(3,), dtype=float64)


In [33]:
multiplication = tf.multiply(x,y)
print(multiplication)
multiplication = x*y
print(multiplication)

tf.Tensor([ 18 128 200], shape=(3,), dtype=int32)
tf.Tensor([ 18 128 200], shape=(3,), dtype=int32)


In [34]:
z = tf.tensordot(x,y,axes=1)
print(z)

tf.Tensor(346, shape=(), dtype=int32)


In [35]:
z = tf.reduce_sum(x*y,axis=0)
print(z)

tf.Tensor(346, shape=(), dtype=int32)


In [36]:
a = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
b = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
matrix_product = tf.matmul(a,b)
print(matrix_product)

tf.Tensor(
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]], shape=(3, 3), dtype=int32)


In [37]:
print(a,"\n",b)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32) 
 tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [40]:
a = tf.constant([[1,2,3],[4,5,6]])
print(a)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [42]:
a = tf.reshape(a,(3,2))
print(a)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [47]:
a = tf.transpose(a)
print(a)

tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)
